# Generated by Django 5.0.1 on 2024-01-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVendedor', models.CharField(max_length=20, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('precio', models.FloatField()),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('imagenMoto', models.ImageField(blank=True, null=True, upload_to='imgMotos', verbose_name='Imagen de moto')),
                ('localidad', models.CharField(max_length=80)),
                ('fechaFabricacion', models.DateField(auto_now_add=True)),
                ('kilometros', models.IntegerField()),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaModificacion', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['marca', 'localidad'],
            },
        ),
    ]
