# Generated by Django 5.0.1 on 2024-01-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moto',
            name='fechaFabricacion',
            field=models.DateField(),
        ),
    ]
