# Generated by Django 5.0 on 2023-12-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='inversor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piso',
            name='imagenPiso',
            field=models.ImageField(blank=True, null=True, upload_to='imgPiso', verbose_name='Imagen de piso'),
        ),
    ]
