# Generated by Django 5.0.1 on 2024-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_equipo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='competicion',
            field=models.ManyToManyField(to='principal.competicion', verbose_name='Competicion'),
        ),
    ]
