# Generated by Django 5.0.1 on 2024-01-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_equipo_competicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='competicion',
            name='lugar',
            field=models.CharField(max_length=50, verbose_name='Lugar de la competicion'),
        ),
        migrations.AlterField(
            model_name='competicion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre de la competicion'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del jugador'),
        ),
    ]
